### PR TITLE
feat: Add Neo4j Adapter

### PR DESCRIPTION
**Pull request by polarvoid**
Hey, I'm working on the Neo4j adapter for Utopia. I'd love some help getting this going.

Currently I'm facing the following issues:
- Getting a test environment going to check progress.
- Translating Graph DB concepts 1:1 to the current Adapter implementation.
- Possibly not doing things the most efficient way.

I'd appreciate any help and feedback on this :)

### CODE REVIEW

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by polarvoid** [comment]
Yep, I'd love some help with this PR, but I plan on implementing it and getting it merged for sure!

**Comment by abnegate** [comment]
Hey @polarvoid are you still working on this?

**Comment by abnegate** [comment]
Closing for now, @polarvoid please re-open if you complete the work on this

**Pull request closed without merging**
