### PR TITLE
doc-4399-removed_Authors

### PR DESCRIPTION
**Pull request by Yashsomalkar**
https://github.com/appwrite/appwrite/issues/4399#issue-1402869442

I have removed all the mentions of the Authors
. Its issue number 4399 in the main repo. @Meldiron @abnegate

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
Thanks for the PR 😇 Your PR looks great, but let's please put the original `composer.lock` file here - we didn't need to remove authors from this file.

Lockfile includes author mentions of dependencies of this library, which might be necessary by their license. 

Once you put `composer.lock` back to original state, I can mark this PR as approved 🤞

**Comment by Yashsomalkar** [comment]
> Thanks for the PR 😇 Your PR looks great, but let's please put the original `composer.lock` file here - we didn't need to remove authors from this file.
> 
> Lockfile includes author mentions of dependencies of this library, which might be necessary by their license. 
> 
> Once you put `composer.lock` back to original state, I can mark this PR as approved 🤞

I knew it something  as fishy. I should have asked 😅. I will do it asap

**Review by Meldiron — APPROVED** [review]
Looks great 🎉

**Comment by Yashsomalkar** [comment]
> Looks great 🎉

Is there any other bigginer issue to work on ?

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
