### PR TITLE
Feat 4375: Add phpStan Code Analyser 

### PR DESCRIPTION
**Pull request by PrerakMathur20**
- [x] Fixes https://github.com/appwrite/appwrite/issues/4375
- [x] Added PhpStan Code Analyzer with **CodeQL Analysis**.

### CODE REVIEW

**Review by stnguyen90 — APPROVED** [review]
Part of the issue required fixing the problems detected by PHPStan, but because there are so many active changes going on with the utopia-php/database repo, I think it's best not to require that and we'll have someone from the core team fix the errors and merge the change ASAP to minimize merge conflicts.

**Comment by stnguyen90** [comment]
Btw, for core:

| Level | Errors|
| --- | --- |
| max/10 | 635 |
| 8 | 462 |
| 7 | 458 |
| 6 | 420 |
| 5 | 92 |
| 3 | 38 |
| 0 | 3 |

**Comment by abnegate** [comment]
@PrerakMathur20 Would you be able to try addressing the issues detected by PHPStan now that the repository is not as busy?

**Comment by abnegate** [comment]
Closing for now due to inactivity

**Pull request closed without merging**
