### PR TITLE
Throw exception on `create` when database already exists

### PR DESCRIPTION
**Pull request by abnegate**
If database already exists but the utopia required collections, attributes and indices do not; continue to create them anyway

### CODE REVIEW

**Review by kodumbeats — APPROVED** [review]

**Comment by eldadfux** [comment]
Would it make sense if we just throw an exception when this conflict happens?

**Comment by abnegate** [comment]
I think either way makes sense, but from my perspective continuing with creation lowers the barrier of entry

**Comment by eldadfux** [comment]
@abnegate after chatting about this with @kodumbeats, I think we should go with an exception for better consistency.

**Comment by abnegate** [comment]
@eldadfux No worries have updated to throw now

**Comment by kodumbeats** [comment]
Force-pushed to rebase `fix-db-exists` on `main` to check tests.

**Pull request closed without merging**
