### PR TITLE
Indexes for permissions

### PR DESCRIPTION
**Pull request by fogelito**

### CODE REVIEW

**Comment by abnegate** [comment]
@fogelito Coming back to this PR, will we need a migration on the Appwrite side for this?

**Comment by fogelito** [comment]
True, looks like the MariaDB
INDEX `_permission` (`_permission`,`_type`,`_document`)

**Comment by abnegate** [comment]
Let's bring this PR up to date and start a corresponding Appwrite PR that includes a migration :+1:

**Review by abnegate — APPROVED** [review]
Do we have a PR open for the migration on Appwrite yet? Please link it to here and we can merge once both are ready :+1:

**Comment by fogelito** [comment]
No.. Will need some help with this.

**Pull request merged**
