### PR TITLE
Added code linter

### PR DESCRIPTION
**Pull request by abhishek-sultaniya**
Fixes [issue 4352](https://github.com/appwrite/appwrite/issues/4352)

### CODE REVIEW

**Review by Meldiron — COMMENTED** [review]
PR looks good to me regarding the main changes. Please allow us some more time to go over all changes to ensure no logic was broken by the linter changes.

**Comment by abhishek-sultaniya** [comment]
> PR looks good to me regarding the main changes. Please allow us some more time to go over all changes to ensure no logic was broken by the linter changes.

Does it need any change?

**Comment by stnguyen90** [comment]
@abhishek-sultaniya, did you just run the format and check everything in?

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by abhishek-sultaniya** [comment]
> @abhishek-sultaniya, did you just run the format and check everything in?

Yup,I tried that.

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
@abhishek-sultaniya would you please revert your auto format changes so that you only have the workflow and composer changes (fixing the merge conflicts as well)? Since there are so many changes to the library, it would be best for someone on the core team to run the formatter and merge ASAP to reduce conflicts.

**Comment by abhishek-sultaniya** [comment]
> @abhishek-sultaniya would you please revert your auto format changes so that you only have the workflow and composer changes (fixing the merge conflicts as well)? Since there are so many changes to the library, it would be best for someone on the core team to run the formatter and merge ASAP to reduce conflicts.

Please could you explain how can I revert the auto formatter changes.

**Comment by stnguyen90** [comment]
@abhishek-sultaniya, maybe this will help: https://stackoverflow.com/questions/4795600/reverting-part-of-a-commit-with-git

**Comment by abnegate** [comment]
Closing for now due to inactivity

**Pull request closed without merging**
